services:
    prometheusdbexporter:
        build:
            context: .
            dockerfile: prometheus.db.exporter.docker
        image: rtsl/prometheusdbexporter:${project.version}
            