services:
    prometheusdbexporter:
        image: simpledotorg/prometheusdbexporter:${PROJECT_VERSION}
        build:
            context: ..
            dockerfile: ./docker_build/prometheus.db.exporter.docker
            args:
                PROJECT_VERSION: ${PROJECT_VERSION}
