services:
  database:
    image: ghcr.io/baosystems/postgis:12-3.3
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_USER: dhis
      POSTGRES_DB: dhis
      POSTGRES_PASSWORD: &postgres_password dhis
      PGPASSWORD: *postgres_password # needed by psql in healthcheck
    healthcheck:
      test: ["CMD-SHELL", "psql --no-password --quiet --username $$POSTGRES_USER postgres://127.0.0.1/$$POSTGRES_DB -p 5432 --command \"SELECT 'ok'\" > /dev/null"]
      start_period: 120s
      interval: 1s
      timeout: 3s
      retries: 5
    
  prometheusdbexporter:
    image: simpledotorg/prometheusdbexporter:0.0.0
    ports:
      - 127.0.0.1:8080:8080
    environment:
      TODO: tada
      TIDI: tudu
      POSTGRES_PASSWORD: &postgres_password dhis
      PGPASSWORD: *postgres_password # needed by psql in healthcheck
    volumes:
    - ./target/tmp:/tmp
    - ./sources:/app/rtsl/prom_db_exporter/sources
      
      
