
name: Build and publish docker image

on:
  push:
    branches:
      - '**'        # matches every branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: 'maven'
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_SIMPLEDOTORG_USERNAME}}
          password: ${{secrets.DOCKERHUB_SIMPLEDOTORG_ACCESS_TOCKEN}}
      - uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.6
      - name: Sets up version
        working-directory: rtsl_util
        run: mvn versions:set -DnewVersion=${{github.ref_name}}.${{github.run_number}}
      - name: Builds Artifacts and Images
        working-directory: rtsl_util
        run: mvn clean install
      - name: Lists all docker images
        working-directory: rtsl_util
        run:  docker image list
      - name: Publish Images
        working-directory: rtsl_util
        run:  docker push simpledotorg/prometheusdbexporter:${{github.ref_name}}.${{github.run_number}}



       




        
