name: Release DHIS2 Verifier
on:
  tag:
    - v*
jobs:
  release-dhis2-verifier:
    defaults:
      run:
        working-directory: CommonUtils/Dhis2CucumberTestTool
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests=true
      - name: Prepare Release Artefacts
        run: |
          mkdir release-artefacts
          cp target/Dhis2CucumberTestTool*.jar release-artefacts  # hardcoded name of the super-jar
          cp target/classes/exec.sh target/classes/input.properties target/classes/log-config.xml release-artefacts
      - name: Zip the Release Artefacts
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r release-artefacts.zip release-artefacts
      - name: Create a release with the artefacts  # Note: this would create a new release…
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "release-artefacts.zip"
          token: ${{ github.token }}
