name: Release DHIS2 Verifier
on:
  push:
    tags:
      - v*
jobs:
  release-dhis2-verifier:
    defaults:
      run:
        working-directory: CommonUtils/Dhis2CucumberTestTool
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: Set the version
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          mvn versions:set -DnewVersion=${{ env.RELEASE_VERSION }}
      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests=true
      - name: Create a release with the artefacts  # Note: this would create a new release…
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "target/Dhis2CucumberTestTool-${{ env.RELEASE_VERSION }}-release.zip"
          token: ${{ github.token }}
